t = input('Digite algo:')
print(type(t))
print('É um número?')
print(t.isnumeric())
print('É uma palavra?')
print(t.isalpha())
print('É alfanúmerico?')
print(t.isalnum())
print('Só tem espaço?')
print(t.isspace())
print('Está em Maiúsculas?')
print(t.isupper())
print('Está em Minúscula?')
print(t.islower())
print('Está Capitalizada?')
print(t.istitle())